ebook_metadata:
  title: ༄༅། །མི་ཤེས་མུན་པ་མཐུག་པོ་སེལ་བའི་ལམ་རིམ་གསལ་བའི་སྒྲོན་མེ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  sku: SHE-SHAP-17
  layers:
  - book_title
  - author
  - quotation
web_metadata:
  title:
    en: The Lamp That Illuminates the Graded Path for Dispelling the Darkness of Ignorance
    bo: མི་ཤེས་མུན་པ་མཐུག་པོ་སེལ་བའི་ལམ་རིམ་གསལ་བའི་སྒྲོན་མེ་བཞུགས་སོ།
  collection:
    en: Shabkar Series–  Book 17
    bo: ཞབས་དཀར་གསུང་འབུམ།–  དེབ། ༡༧
  author:
    en: Shabkar Tsokdruk Rangdrol
    bo: ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SHAP-17
  category:
    en: Stages of the Path
    bo: ལམ་རིམ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SHAP-17.epub
  description:
    en: ''
    bo: ''
